services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: apkraft_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: crpi-wcfdnsi88pmwqij1.cn-hangzhou.personal.cr.aliyuncs.com/akatsukii/apkraft-cli:latest
    ports:
      - "80:3000"
    environment:
      DATABASE_URL: "postgres://loco:loco@postgres:5432/apkraft_production"
    depends_on:
      - postgres
    restart: on-failure
    restart_policy:
      delay: 10s
      max_attempts: 5
      window: 60s

volumes:
  postgres_data:
