//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.9

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "app_versions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version_code: String,
    pub version_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub release_notes: Option<String>,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub app_id: i32,
    pub apk_file_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::apk_files::Entity",
        from = "Column::ApkFileId",
        to = "super::apk_files::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ApkFiles,
    #[sea_orm(
        belongs_to = "super::apps::Entity",
        from = "Column::AppId",
        to = "super::apps::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Apps,
}

impl Related<super::apk_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApkFiles.def()
    }
}

impl Related<super::apps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apps.def()
    }
}
