//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.9

pub use super::app_versions::Entity as AppVersions;
pub use super::apps::Entity as Apps;
pub use super::files::Entity as Files;
pub use super::platforms::Entity as Platforms;
pub use super::users::Entity as Users;
